ignore: []

refactor:
  skip: []

metrics:
  enabled: true
  quality_threshold: 7.0

github:
  labels: []
  ignore_labels: [sourcery-ignore]
  request_review: author
  sourcery_branch: sourcery/{base_branch}