"""empty message

Revision ID: 2865a6b340e5
Revises: 72a6ae474afc
Create Date: 2020-01-13 17:02:05.152584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2865a6b340e5'
down_revision = '72a6ae474afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration', sa.Column('config_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration', 'config_order')
    # ### end Alembic commands ###
